# This workflow is to update the kubernetes deployment app to initate GITOPS

name: argo-update

on: create
#  push:
#    paths:
#    - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Export tag version
        run: |
          latest_tag=`git describe --tags|awk -F- '{print $1}'`
          echo "ltag=$latest_tag" >> $GITHUB_ENV 
      - name: Docker hub login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: karthick-kk/github-runner:${{ ltag }}
      - uses: actions/checkout@master
        with:
          repository: karthick-kk/argo-githubrunner
          token: ${{ secrets.GITKEN }}
      - name: Update deployment image version of k8
        run: |
          sed -i 's/\(github-runner:\).*/\1'"$ltag"'/g' github-runner/deployments/runner.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITKEN }}
          repository: karthick-kk/argo-githubrunner
          branch: ${{ github.ref }}
